application: trendblotter-dev
version: 1
runtime: python27
api_version: 1
threadsafe: no

skip_files: |
 ^(.*/)?(
 (app\.yaml)|
 (app\.yml)|
 (#.*#)|
 (.*~)|
 (.*\.py[co])|
 (.*/RCS/.*)|
 (\..*)|
 )$

builtins:
- appstats: on
- remote_api: on

admin_console:
  pages:
  - name: Appstats
    url: /_ah/stats/

libraries:
- name: jinja2
  version: "2.6"
- name: markupsafe
  version: "0.15"
- name: webapp2
  version: latest
- name: PIL
  version: latest
- name: lxml
  version: latest

handlers:
- url: /favicon.ico
  static_files: blotter/static/img/favicon.ico
  upload: blotter/static/img/favicon.ico

- url: /robots.txt
  static_files: blotter/static/robots.txt
  upload: blotter/static/robots.txt

- url: /static
  static_dir: blotter/static

- url: /_ah/queue/async.*
  script: furious_router.app
  login: admin

- url: /aggregate
  script: main.app
  login: admin

- url: .*
  script: main.app
